# Generated by Django 6.0.2 on 2026-02-04 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_request_numbers(apps, schema_editor):
    CollectionRequest = apps.get_model('collection', 'CollectionRequest')
    from collections import defaultdict
    seen = defaultdict(int)
    for req in CollectionRequest.objects.order_by('created_at'):
        if not req.request_number:
            date_part = req.created_at.date() if req.created_at else timezone.now().date()
            seen[date_part] += 1
            req.request_number = f'REQ-{date_part:%Y%m%d}-{seen[date_part]:04d}'
            req.save(update_fields=['request_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='estimated_collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for company (not visible to institution)'),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='request_number',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.RunPython(backfill_request_numbers, migrations.RunPython.noop),
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
