# Generated by Django 6.0.2 on 2026-02-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_add_urgency_notes_request_number_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('paper', 'Бумага'), ('cardboard', 'Картон'), ('newspapers', 'Газеты'), ('mixed', 'Смешанная'), ('archive', 'Архивная')], max_length=20)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='actual_collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='estimated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='material_type',
            field=models.CharField(choices=[('paper', 'Бумага'), ('cardboard', 'Картон'), ('newspapers', 'Газеты'), ('mixed', 'Смешанная'), ('archive', 'Архивная')], default='paper', max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='bik',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='corr_account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='inn',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='kpp',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='legal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.FileField(blank=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='access_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='contact_person_on_site',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='container_location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='inn',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='kpp',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='legal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='phone_on_site',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='preferred_days',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='preferred_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('company', 'Collection Company'), ('institution', 'Institution')], default='company', max_length=20),
        ),
    ]
