# Generated by Django 6.0.2 on 2026-02-08 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_admin_role_pricelist_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='paper_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='RequestMaterialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('paper', 'Бумага'), ('cardboard', 'Картон'), ('newspapers', 'Газеты'), ('mixed', 'Смешанная'), ('archive', 'Архивная')], max_length=20)),
                ('amount_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lines', to='collection.collectionrequest')),
            ],
            options={
                'verbose_name': 'Request Material Line',
                'verbose_name_plural': 'Request Material Lines',
            },
        ),
    ]
