# Generated by Django 4.2+

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_add_news_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionprofile',
            name='company_notes',
            field=models.TextField(
                blank=True,
                help_text='Заметка компании об организации (редактирует только компания)',
            ),
        ),
    ]
