# Generated by Django 4.2+

from decimal import Decimal
from django.db import migrations, models


def create_default_limit(apps, schema_editor):
    RequestWeightLimit = apps.get_model('collection', 'RequestWeightLimit')
    RequestWeightLimit.objects.get_or_create(
        pk=1,
        defaults={'min_kg': Decimal('100'), 'max_kg': Decimal('100000')},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_institutionprofile_company_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestWeightLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_kg', models.DecimalField(decimal_places=2, default=100, help_text='Минимальный суммарный вес заявки (кг)', max_digits=10)),
                ('max_kg', models.DecimalField(decimal_places=2, default=100000, help_text='Максимальный суммарный вес заявки (кг)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Лимит веса заявок',
                'verbose_name_plural': 'Лимиты веса заявок',
            },
        ),
        migrations.RunPython(create_default_limit, migrations.RunPython.noop),
    ]
