# Generated by Django (bonus system)

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_bonus_config(apps, schema_editor):
    BonusConfig = apps.get_model('collection', 'BonusConfig')
    BonusConfig.objects.get_or_create(pk=1, defaults={'bonus_percent': Decimal('0')})


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0007_requestweightlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_percent', models.DecimalField(decimal_places=2, default=0, help_text='Процент бонуса от суммы заявки (например 1.00 = 1%)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Настройка бонусов',
                'verbose_name_plural': 'Настройки бонусов',
            },
        ),
        migrations.CreateModel(
            name='InstitutionBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, help_text='Сумма по расчёту (стоимость заявки × процент)', max_digits=12)),
                ('awarded_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Фактически начисленная сумма (может изменить администратор)', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Начислен')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_bonus', to='collection.collectionrequest')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_bonuses', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='collection.institutionprofile')),
            ],
            options={
                'verbose_name': 'Бонус организации',
                'verbose_name_plural': 'Бонусы организаций',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(create_bonus_config, migrations.RunPython.noop),
    ]
