# Generated by Django 5.2.11 on 2026-02-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_institution_registration_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят'), ('completed', 'Доставлен'), ('cancelled', 'Отменён')], default='pending', max_length=20),
        ),
    ]
