# Generated by Django 5.2.12 on 2026-03-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0016_pricelist_material_oneToOne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['material__name'], 'verbose_name': 'Price List', 'verbose_name_plural': 'Price Lists'},
        ),
    ]
