# Generated by Django 5.2.12 on 2026-04-01 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_alter_pricelist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionregistrationrequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, db_index=True, max_length=20)),
                ('action_type', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('target_model', models.CharField(blank=True, db_index=True, max_length=120)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('short_summary', models.CharField(max_length=255)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аудит действия',
                'verbose_name_plural': 'Аудит действий',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='collection__created_8d475a_idx'), models.Index(fields=['actor_role', 'created_at'], name='collection__actor_r_693ef6_idx'), models.Index(fields=['category', 'created_at'], name='collection__categor_20be5e_idx'), models.Index(fields=['target_model', 'target_id'], name='collection__target__32cef5_idx')],
            },
        ),
    ]
