# Generated by Django 5.2.12 on 2026-04-03 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0018_institutionregistrationrequest_email_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Administrator'),
                    ('company', 'Collection Company'),
                    ('institution', 'Institution'),
                    ('support', 'Technical Support'),
                ],
                default='company',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='support_user',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'role': 'support'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='supported_institutions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='SupportChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chat_messages', to='collection.institutionprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chat_sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение техподдержки',
                'verbose_name_plural': 'Сообщения техподдержки',
                'ordering': ['created_at'],
                'indexes': [
                    models.Index(fields=['institution', 'created_at'], name='collecti_institu_0fdca2_idx'),
                    models.Index(fields=['institution', 'is_read'], name='collecti_institu_9db268_idx'),
                ],
            },
        ),
    ]
