# Generated by Django 5.2.12 on 2026-05-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0020_material_catalog_public_pickup'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportchatmessage',
            new_name='collection__institu_0ba30f_idx',
            old_name='collecti_institu_0fdca2_idx',
        ),
        migrations.RenameIndex(
            model_name='supportchatmessage',
            new_name='collection__institu_0cd11d_idx',
            old_name='collecti_institu_9db268_idx',
        ),
    ]
