# Generated by Django 5.2.12 on 2026-06-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0026_request_pending_confirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__sort_order', 'name'], 'verbose_name': 'Товар (баллы)', 'verbose_name_plural': 'Товары (баллы)'},
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('pending_confirmation', 'Pending confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
